semilla_primigenia: 700001.0
experimento: 6300_generencia_FE_newApproach
dataset: gerencial_competencia_2025.csv.gz
DR:
  metodo: deflacion
FE_rf:
  arbolitos: 20.0
  hojas_por_arbol: 16.0
  datos_por_hoja: 100.0
  mtry_ratio: 0.2
  train:
    clase01_valor1:
    - BAJA+2
    - BAJA+1
    training:
    - 202101.0
    - 202102.0
    - 202103.0
  lgb_param:
    num_iterations: 20.0
    num_leaves: 16.0
    min_data_in_leaf: 100.0
    feature_fraction_bynode: 0.2
    boosting: rf
    bagging_fraction: 0.6321206
    bagging_freq: 1.0
    feature_fraction: 1.0
    max_bin: 31
    objective: binary
    first_metric_only: yes
    boost_from_average: yes
    feature_pre_filter: no
    force_row_wise: yes
    verbosity: -100.0
    max_depth: -1
    min_gain_to_split: 0.0
    min_sum_hessian_in_leaf: 0.001
    lambda_l1: 0.0
    lambda_l2: 0.0
    pos_bagging_fraction: 1.0
    neg_bagging_fraction: 1.0
    is_unbalance: no
    scale_pos_weight: 1.0
    drop_rate: 0.1
    max_drop: 50.0
    skip_drop: 0.5
    extra_trees: no
CN:
  ratio: 0.2
  desvios: 2.0
  train:
    clase01_valor1:
    - BAJA+2
    - BAJA+1
    positivos: BAJA+2
    training:
    - 202101.0
    - 202102.0
    - 202103.0
    validation: 202105.0
    undersampling: 0.1
    gan1: 117000.0
    gan0: -3000.0
FE_GENALG:
  generations: 100.0
  population: 50.0
  new_variables: 25.0
  max_depth: 5.0
  semillas:
  - 405799
  - 729637
  - 136951
  - 962561
  - 927301
  - 726629
  - 301141
  - 997433
  - 583273
  - 280487
  - 907757
  - 180491
  - 925147
  - 710023
  - 111611
  - 884699
  - 595087
  - 237379
  - 309737
  - 827423
  - 292969
  - 166609
  - 315691
  - 833737
  - 623767
  - 522887
  - 166157
  - 224591
  - 708403
  - 391351
  - 315461
  - 955183
  - 745543
  - 217069
  - 817793
  - 502259
  - 225067
  - 266671
  - 826927
  - 520433
  - 580219
  - 901963
  - 149309
  - 484193
  - 852689
  - 210361
  - 393361
  - 207653
  - 666233
  - 235577
  - 294829
  - 390209
  - 506663
  - 257249
  - 856081
  - 414763
  - 341851
  - 464897
  - 565867
  - 778091
  - 344683
  - 652871
  - 632321
  - 815663
  - 117839
  - 331369
  - 643847
  - 409237
  - 107647
  - 575711
  - 208037
  - 664879
  - 287597
  - 652999
  - 778717
  - 260543
  - 313241
  - 261641
  - 145513
  - 916633
  - 539153
  - 309293
  - 951427
  - 749393
  - 984119
  - 654917
  - 105619
  - 880027
  - 745201
  - 440047
  - 504403
  - 386537
  - 835001
  - 930817
  - 442207
  - 398941
  - 866909
  - 400291
  - 276869
  - 758243
trainingstrategy:
  validate: 202107.0
  training:
  - 202106.0
  - 202105.0
  - 202104.0
  - 202103.0
  - 202102.0
  - 202101.0
  - 202012.0
  - 202011.0
  - 202010.0
  - 202009.0
  - 202008.0
  - 202007.0
  - 202006.0
  - 202005.0
  training_pct: 1.0
  positivos:
  - BAJA+1
  - BAJA+2
  final_train:
  - 202107.0
  - 202106.0
  - 202105.0
  - 202104.0
  - 202103.0
  - 202102.0
  - 202101.0
  - 202012.0
  - 202011.0
  - 202010.0
  - 202009.0
  - 202008.0
  - 202007.0
  - 202006.0
  - 202005.0
  future: 202109.0
hipeparametertuning:
  num_interations: 55.0
  hs:
    pars:
      num_leaves:
        id: num_leaves
        type: integer
        len: 1
        lower: 500
        upper: 1500
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
      min_data_in_leaf:
        id: min_data_in_leaf
        type: integer
        len: 1
        lower: 8
        upper: 250
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
      learning_rate:
        id: learning_rate
        type: numeric
        len: 1
        lower: 0.01
        upper: 0.1
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
      feature_fraction:
        id: feature_fraction
        type: numeric
        len: 1
        lower: 0.1
        upper: 0.4
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
    forbidden: ~
lgbm:
  param_fijos:
    objective: binary
    metric: auc
    first_metric_only: yes
    boost_from_average: yes
    feature_pre_filter: no
    verbosity: -100.0
    force_row_wise: yes
    seed: 700001.0
    max_bin: 31.0
    num_iterations: 2048.0
    early_stopping_rounds: 200.0
out:
  lgbm:
    mejores_hiperparametros:
      num_leaves: 819
      min_data_in_leaf: 20
      num_iterations: 728
      learning_rate: 0.0179887
      feature_fraction: 0.2196912
kaggle:
  competencia: data-mining-gerencial-2025-a
  cortes:
  - 800.0
  - 850.0
  - 900.0
  - 950.0
  - 1000.0
  - 1050.0
  - 1100.0
  - 1150.0
  - 1200.0
  - 1250.0
  - 1300.0
